mysql mtomi-db < /home/mtomi/IGAZHIR/mysql_import_scripts/mysql_import_ABC_BBC.sql > /home/mtomi/IGAZHIR/MYSQL/RESULT/ABC_BBC.tsv
mysql mtomi-db < /home/mtomi/IGAZHIR/mysql_import_scripts/mysql_import_ABC_CNN.sql > /home/mtomi/IGAZHIR/MYSQL/RESULT/ABC_CNN.tsv
mysql mtomi-db < /home/mtomi/IGAZHIR/mysql_import_scripts/mysql_import_ABC_REUTERS.sql > /home/mtomi/IGAZHIR/MYSQL/RESULT/ABC_REUTERS.tsv
mysql mtomi-db < /home/mtomi/IGAZHIR/mysql_import_scripts/mysql_import_ABC_NBC.sql > /home/mtomi/IGAZHIR/MYSQL/RESULT/ABC_NBC.tsv
mysql mtomi-db < /home/mtomi/IGAZHIR/mysql_import_scripts/mysql_import_ABC_NPR.sql > /home/mtomi/IGAZHIR/MYSQL/RESULT/ABC_NPR.tsv
mysql mtomi-db < /home/mtomi/IGAZHIR/mysql_import_scripts/mysql_import_ABC_GUARDIAN.sql > /home/mtomi/IGAZHIR/MYSQL/RESULT/ABC_GUARDIAN.tsv
mysql mtomi-db < /home/mtomi/IGAZHIR/mysql_import_scripts/mysql_import_ABC_FOX.sql > /home/mtomi/IGAZHIR/MYSQL/RESULT/ABC_FOX.tsv
mysql mtomi-db < /home/mtomi/IGAZHIR/mysql_import_scripts/mysql_import_CNN_BBC.sql > /home/mtomi/IGAZHIR/MYSQL/RESULT/CNN_BBC.tsv
mysql mtomi-db < /home/mtomi/IGAZHIR/mysql_import_scripts/mysql_import_BBC_REUTERS.sql > /home/mtomi/IGAZHIR/MYSQL/RESULT/BBC_REUTERS.tsv
mysql mtomi-db < /home/mtomi/IGAZHIR/mysql_import_scripts/mysql_import_BBC_NBC.sql > /home/mtomi/IGAZHIR/MYSQL/RESULT/BBC_NBC.tsv
mysql mtomi-db < /home/mtomi/IGAZHIR/mysql_import_scripts/mysql_import_BBC_NPR.sql > /home/mtomi/IGAZHIR/MYSQL/RESULT/BBC_NPR.tsv
mysql mtomi-db < /home/mtomi/IGAZHIR/mysql_import_scripts/mysql_import_BBC_GUARDIAN.sql > /home/mtomi/IGAZHIR/MYSQL/RESULT/BBC_GUARDIAN.tsv
mysql mtomi-db < /home/mtomi/IGAZHIR/mysql_import_scripts/mysql_import_BBC_FOX.sql > /home/mtomi/IGAZHIR/MYSQL/RESULT/BBC_FOX.tsv
mysql mtomi-db < /home/mtomi/IGAZHIR/mysql_import_scripts/mysql_import_CNN_REUTERS.sql > /home/mtomi/IGAZHIR/MYSQL/RESULT/CNN_REUTERS.tsv
mysql mtomi-db < /home/mtomi/IGAZHIR/mysql_import_scripts/mysql_import_CNN_NBC.sql > /home/mtomi/IGAZHIR/MYSQL/RESULT/CNN_NBC.tsv
mysql mtomi-db < /home/mtomi/IGAZHIR/mysql_import_scripts/mysql_import_CNN_NPR.sql > /home/mtomi/IGAZHIR/MYSQL/RESULT/CNN_NPR.tsv
mysql mtomi-db < /home/mtomi/IGAZHIR/mysql_import_scripts/mysql_import_CNN_GUARDIAN.sql > /home/mtomi/IGAZHIR/MYSQL/RESULT/CNN_GUARDIAN.tsv
mysql mtomi-db < /home/mtomi/IGAZHIR/mysql_import_scripts/mysql_import_CNN_FOX.sql > /home/mtomi/IGAZHIR/MYSQL/RESULT/CNN_FOX.tsv
mysql mtomi-db < /home/mtomi/IGAZHIR/mysql_import_scripts/mysql_import_REUTERS_NBC.sql > /home/mtomi/IGAZHIR/MYSQL/RESULT/REUTERS_NBC.tsv
mysql mtomi-db < /home/mtomi/IGAZHIR/mysql_import_scripts/mysql_import_REUTERS_NPR.sql > /home/mtomi/IGAZHIR/MYSQL/RESULT/REUTERS_NPR.tsv
mysql mtomi-db < /home/mtomi/IGAZHIR/mysql_import_scripts/mysql_import_REUTERS_GUARDIAN.sql > /home/mtomi/IGAZHIR/MYSQL/RESULT/REUTERS_GUARDIAN.tsv
mysql mtomi-db < /home/mtomi/IGAZHIR/mysql_import_scripts/mysql_import_REUTERS_FOX.sql > /home/mtomi/IGAZHIR/MYSQL/RESULT/REUTERS_FOX.tsv
mysql mtomi-db < /home/mtomi/IGAZHIR/mysql_import_scripts/mysql_import_NBC_NPR.sql > /home/mtomi/IGAZHIR/MYSQL/RESULT/NBC_NPR.tsv
mysql mtomi-db < /home/mtomi/IGAZHIR/mysql_import_scripts/mysql_import_NBC_GUARDIAN.sql > /home/mtomi/IGAZHIR/MYSQL/RESULT/NBC_GUARDIAN.tsv
mysql mtomi-db < /home/mtomi/IGAZHIR/mysql_import_scripts/mysql_import_NBC_FOX.sql > /home/mtomi/IGAZHIR/MYSQL/RESULT/NBC_FOX.tsv
mysql mtomi-db < /home/mtomi/IGAZHIR/mysql_import_scripts/mysql_import_NPR_GUARDIAN.sql > /home/mtomi/IGAZHIR/MYSQL/RESULT/NPR_GUARDIAN.tsv
mysql mtomi-db < /home/mtomi/IGAZHIR/mysql_import_scripts/mysql_import_NPR_FOX.sql > /home/mtomi/IGAZHIR/MYSQL/RESULT/NPR_FOX.tsv
mysql mtomi-db < /home/mtomi/IGAZHIR/mysql_import_scripts/mysql_import_GUARDIAN_FOX.sql > /home/mtomi/IGAZHIR/MYSQL/RESULT/GUARDIAN_FOX.tsv